name: Create branch with only changed files

on:
  pull_request:
    types: [closed]

jobs:
  create-changes-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push branches

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need history for diff

      - name: Get list of changed files
        id: changes
        run: |
          git fetch origin main
          git diff --name-only origin/main HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Create temporary folder with changed files
        run: |
          mkdir changed_only
          while IFS= read -r file; do
            mkdir -p "changed_only/$(dirname "$file")"
            cp "$file" "changed_only/$file" 2>/dev/null || true
          done < changed_files.txt

      - name: Create new branch with only changed files
        run: |
          cd changed_only
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b changes-from-${{ github.run_number }}
          git add .
          git commit -m "New branch with only changed files from PR #${{ github.event.pull_request.number }}"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin changes-from-${{ github.run_number }}
