name: Create branch with only changed files

on:
  pull_request:
    types: [closed]

jobs:
  create-changes-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push new branches

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed files from merge commit (excluding workflows)
        id: changes
        run: |
          echo "Finding files changed in this merge..."
          # exclude any .github/workflows/ files
          git diff --name-only HEAD^ HEAD | grep -v '^.github/workflows/' > changed_files.txt || true
          echo "Changed files:"
          cat changed_files.txt || echo "No changed files found."

          if [ ! -s changed_files.txt ]; then
            echo "No changed files found. Exiting gracefully."
            exit 0
          fi

      - name: Create temporary folder and copy changed files
        run: |
          mkdir changed_only
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              mkdir -p "changed_only/$(dirname "$file")"
              cp "$file" "changed_only/$file"
            fi
          done < changed_files.txt
          echo "Files copied:"
          ls -R changed_only || echo "No files copied."

      - name: Create and push new branch with only changed files
        run: |
          cd changed_only
          git init -b main
          git config user.name "subbarajubnsr-dev"
          git config user.email "subbaraju.bnsr@gmail.com"

          BRANCH_NAME="changes-from-pr-${{ github.event.pull_request.number }}-${{ github.run_number }}"
          git checkout -b "$BRANCH_NAME"

          git add .
          git commit -m "New branch with only changed files from PR #${{ github.event.pull_request.number }}"

          git remote add origin https://x-access-token:${{ secrets.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 }}@github.com/${{ github.repository }}.git
          git push origin "$BRANCH_NAME"

      - name: Summary
        run: |
          echo "✅ Successfully created and pushed branch: changes-from-pr-${{ github.event.pull_request.number }}-${{ github.run_number }}"
